### ISSUE TITLE
Stderr Stacktrace on stdinchikey sometimes

### ISSUE THREAD

**Issue by tylerperyea** [ncats/molwitch-cdk#6]
org.openscience.cdk.exception.CDKException: Cannot assign Kekulé structure, non-sigma bond order has already been assigned?
	at org.openscience.cdk.aromaticity.Kekulization.kekulize(Kekulization.java:113)
	at gov.nih.ncats.molwitch.cdk.CdkChemicalImpl.lambda$kekulize$15(CdkChemicalImpl.java:979)
	at gov.nih.ncats.molwitch.cdk.CdkChemicalImpl.doWithQueryFixes(CdkChemicalImpl.java:772)
	at gov.nih.ncats.molwitch.cdk.CdkChemicalImpl.kekulize(CdkChemicalImpl.java:977)
	at gov.nih.ncats.molwitch.Chemical.kekulize(Chemical.java:540)
	at gov.nih.ncats.molwitch.cdk.CdkChemicalInchiImplFactory.asStdInchi(CdkChemicalInchiImplFactory.java:94)
	at gov.nih.ncats.molwitch.inchi.Inchi.asStdInchi(Inchi.java:48)
	at gov.nih.ncats.molwitch.Chemical.toInchi(Chemical.java:579)
	at gov.nih.ncats.molvec.internal.algo.experimental.InChIKeySetScorer.score(InChIKeySetScorer.java:98)
	at gov.nih.ncats.molvec.internal.algo.experimental.ModifiedMolvecPipel

I don't know that it should actually throw the exception, but it should probably have a global flag for whether it swallows, throws, or prints. I don't think printing is the right default.

**Comment by dkatzel-ncats** [comment]
Right now it catches and swallows it put prints the stacktrace to stderr. we can use a logger and only print a certain log level?
